### ISSUE TITLE
the other issue I mentioned yesterday about nesting

### ISSUE THREAD

**Issue by stoyicker** [osama-raddad/Warehouse#6]
Osama my friend I'm going to be off for a few days, so before that just something I thought of yesterday night.

    val userwarehouse = warehouse(scope = Scope.CONSUMER) {
        this add namewarehouse
        this add userIDwarehouse
    }

    val consumerServiceLocator = warehouse(scope = Scope.CONSUMER) {
        this add userwarehouse
        this add module {
            this add factory {
                constructor { Access.ADMIN }
            }
        }
    }

That's from your gist yesterday. This line -> ` this add userwarehouse `; you aren't going to be able to do that, and if you could, it'd be a memory leak. Think of the following example:
  * I have an Activity, and a Fragment, which sometimes shows in said Activity. Sometimes is the key word here - imagine it's a dialog or something.
  * The activity is injected by a warehouse, let's call it activityWarehouse. All good thus far.
  * The fragment is injected by a warehouse, let's call it fragmentWarehouse, nested to activityWarehouse because it requires some of its dependencies.
 
With this in mind, your warehouses look somewhat like this:

```
val fragmentWarehouse = ...
val activityWarehouse = warehouse {
  ....
  add fragmentWarehouse
}
```

You're forcing the fragment warehouse to exist whenever the activityWarehouse does, so when the Activity does, rather than the fragment. Hence, until the fragment needs to be injected (if it ever does), you have a memory leak

---------------------------------------------------------------------------------------------------

Furthermore, let's suppose you add something like @BindsInstance, and the fragment wants to use it, idk because for example it binds itself to the graph as a listener of some sort or something. In that case you'd never be able to write the code from above because, well, you don't have a fragment to bind by the time you need it, since this would be creation of fragmentWarehouse -> creation of activityWarehouse - Activity#onCreate (I assume)

You need to make it so it's the fragment who decides when to create its warehouse. Something like:

```
val fragmentWarehouse = warehouse(childTo = requireActivity().warehouse)
```

or

```
val fragmeentWarehouse = requireActivity().warehouse.newFragmentWarehouse()
```

**Comment by osama-raddad** [comment]
Will my friend I hope I got you correctly, if the fragment warehouse depends on the activity warehouse I believe It is more reasonable to write it in this way (which is more valid way)

val activityWarehouse = ...
val fragmentWarehouse = warehouse {
  add activityWarehouse
  …
}

and by the way all of the constructors added to the warehouse are lazy loaded so the constructor declaration is not invoked until it is injected.

**Comment by stoyicker** [comment]
> Will my friend I hope I got you correctly, if the fragment warehouse depends on the activity warehouse I believe It is more reasonable to write it in this way (which is more valid way)

No Osama my friend it's not about aesthetics or a more reasonable API, it's objectively a bug. The warehouse for the fragment can't exist until the fragment does, otherwise if for example the fragment requests an instance of itself (e.g. via something like `bindsInstance`), it can never be provided. Also, the fact that the constructors are lazy may mean you don't leak thee dependencies they create, but you're still leaking the nested warehouse since it's unused until the injection site is created.

**Comment by osama-raddad** [comment]
resolved
